Book_Doctor_appointment/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Book_Doctor_appointment.Models
{
    public class Hospital
    {
    }
}

Book_Doctor_appointment/Models/Myappointments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Book_Doctor_appointment.Models
{
    public class Myappointments
    {

        public string Name { get; set; }

        public string Emailid { get; set; }
        public int Id { get; set; }
        [Display(Name ="Doctor Name")]
        public string DoctorName { get; set; }
        public string Speciality { get; set; }
        public string Location { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date of Appointment")]
        public DateTime? Dateofappointment { get; set; }

        public string Timeslot { get; set; }
        
        public DateTime? Booked_Date { get; set; }
      
    }
}

Book_Doctor_appointment/Controllers/HospitalController.cs
using Book_Doctor_appointment.Models;
using System;
using System.Collections.Generic;
using System.Data.Objects.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Book_Doctor_appointment.Controllers
{
    public class HospitalController : Controller
    {
        public ActionResult Index(int? id)
        {
            List<SelectListItem> locationlist = GetLocations();
            List<SelectListItem> Specialtylist = GetSpecialties();
            ViewBag.location = locationlist;
            ViewBag.Specialty = Specialtylist;
            ViewBag.Userid = id;
            return View();
        }
        private static List<SelectListItem> GetLocations()
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<SelectListItem> locationlist = (from p in entities.Hospital_location.AsEnumerable()
                                                 select new SelectListItem
                                                 {
                                                     Text = p.Hospital_Location1,
                                                     Value = p.id.ToString()
                                                 }).ToList();
            locationlist.Insert(0, new SelectListItem { Text = "--Select Hospital--", Value = "" });

            return locationlist;
        }

        private static List<SelectListItem> GetSpecialties()
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<SelectListItem> Specialtylist = (from p in entities.Specialties.AsEnumerable()
                                                 select new SelectListItem
                                                 {
                                                     Text = p.Specialty1,
                                                     Value = p.id.ToString()
                                                 }).ToList();
            Specialtylist.Insert(0, new SelectListItem { Text = "--Select Specialty--", Value = "" });

            return Specialtylist;
        }

        public ActionResult AllDctor()
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<Alldoctor> listuser = new List<Alldoctor>();
            var listofdoctor = (from p in entities.ListofDoctors
                                join q in entities.Specialties on p.Specialityid equals q.id
                                join r in entities.Hospital_location on p.locid equals r.id
                                select new Alldoctor
                                {
                                    Id = p.id,
                                    Doctorname = p.Doctorname,
                                    Speciality = q.Specialty1,
                                    Location = r.Hospital_Location1

                                }).ToList();
            listuser = listofdoctor.ToList();
             return View(listuser);
        }
        public ActionResult GetListofDoctorforselected(int locid,int spid,int? userid)
        {
            List<SelectListItem> Timeslot = Gettimeslot();
            ViewBag.Timeslot = Timeslot;
            Session["userid"] = userid;
            ViewBag.Userid = userid;
            TempData["Userid"] = userid;
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<Alldoctor> listofdoctor = new List<Alldoctor>();
            listofdoctor = (from p in entities.ListofDoctors
                            join q in entities.Specialties on p.Specialityid equals q.id
                            join r in entities.Hospital_location on p.locid equals r.id
                            where p.Specialityid== spid && r.id==locid
                            select new Alldoctor
                            {
                                Id=p.id,
                                Doctorname = p.Doctorname,
                                Speciality = q.Specialty1,
                                Location=r.Hospital_Location1

                            }).ToList();
            return View(listofdoctor);
        }

        [HttpPost]
        public JsonResult GetDoctor()
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<Alldoctor> listuser = new List<Alldoctor>();
            var listofdoctor = (from p in entities.ListofDoctors
                                join q in entities.Specialties on p.Specialityid equals q.id
                                join r in entities.Hospital_location on p.locid equals r.id
                                select new Alldoctor
                                {
                                    Id = p.id,
                                    Doctorname = p.Doctorname,
                                    Speciality = q.Specialty1,
                                    Location = r.Hospital_Location1

                                }).ToList();
            listuser = listofdoctor.ToList();
            return Json(listuser);

        }

        [HttpGet]
        public ActionResult Bookappointment(int id)
        {
            object Userid = Session["Userid"];
            int ids = (int)Userid;
            List<SelectListItem> Timeslot = Gettimeslot();
            ViewBag.Timeslot = Timeslot;
            ViewBag.Userid = ids;
            ViewBag.DoctorId=id;
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<Appointments> listofdoctor = new List<Appointments>();
            listofdoctor = (from p in entities.ListofDoctors
                            join q in entities.Specialties on p.Specialityid equals q.id
                            join r in entities.Hospital_location on p.locid equals r.id
                            where p.id== id
                            select new Appointments
                            {
                                DoctorName = p.Doctorname,
                                Speciality = q.Specialty1,
                                Location = r.Hospital_Location1

                            }).ToList();
            return View(listofdoctor);
        }

        private static List<SelectListItem> Gettimeslot()
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<SelectListItem> Specialtylist = (from p in entities.Timeslots.AsEnumerable()
                                                  select new SelectListItem
                                                  {
                                                      Text = p.timeslot1,
                                                      Value = p.id.ToString()
                                                  }).ToList();
            Specialtylist.Insert(0, new SelectListItem { Text = "--Select TimeSlot--", Value = "" });

            return Specialtylist;
        }

        public ActionResult Gettimeslotbyavailability(int doctorid,DateTime Date)
        {
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            var data1 = (from p in entities.Timeslots
                         join q in entities.Appointments on p.id equals q.Timeslot
                         where q.Date_of_Appointment == Date && q.Doctorid == doctorid
                         select new
                         {   p.id,
                             p.timeslot1
                         });
            var data2 = (from p in entities.Timeslots
                         join q in entities.ListofDoctors on p.Doctorid equals q.id
                         where p.Doctorid == doctorid
                         select new
                         {  
                             p.id,
                             p.timeslot1      
                         });

            var data3 = (from p in data2 select p).Except(data1);
            List<SelectListItem> availabletimeslots = (from p in data3.AsEnumerable()

                                                       select new  SelectListItem
                                                       { 
                                                           Text = p.timeslot1,
                                                           Value = p.id.ToString()
                                                       }).ToList();
            
            return Json(availabletimeslots, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BookappointmentSucess (DateTime date ,int userid,int doctorid,int timeslotid)
        {
            Session["userid"] = userid;
            ViewBag.Id = userid;
                 HospitalApplicationEntities db = new HospitalApplicationEntities();
                 Appointment rs = new Appointment();
                 rs.Date_of_Appointment = date;
                 rs.Userid = userid;
                 rs.Doctorid = doctorid;
                 rs.Booked_appointment_date = DateTime.Now;
                 rs.Timeslot = timeslotid;
                 db.Appointments.Add(rs);
                 db.SaveChanges();
            ViewBag.Message = "Appointment Booked Sucessfully Please check My Appointments for more details";
            return View("Bookappointment_Sucess");
        }

        public ActionResult Myappointments (int id)
        {
            Session["userid"] = id;
            ViewBag.Userid = id;
            HospitalApplicationEntities entities = new HospitalApplicationEntities();
            List<Myappointments> my_pp = new List<Myappointments>();
             my_pp = (from a in entities.Appointments
                      join b in entities.registers on a.Userid equals b.id
                      join c in entities.ListofDoctors on a.Doctorid equals c.id
                      join d in entities.Hospital_location on c.locid equals d.id
                      join e in entities.Specialties on c.Specialityid equals e.id

Book_Doctor_appointment/Views/Hospital/AllDctor.cshtml
@model IEnumerable<Book_Doctor_appointment.Models.Alldoctor>

@{
    ViewBag.Title = "DoctorsList";
}

<h2>Doctors List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Doctorname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Doctorname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speciality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                <p><a href=""  id="login">Book Appointment &raquo;</a></p>

            </td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $("#login").click(function () {
        debugger;
      
        alert("Please login to Book appointments")

    });

</script>

Book_Doctor_appointment/Views/Hospital/Bookappointment.cshtml
@model IEnumerable<Book_Doctor_appointment.Models.Appointments>


@{
    ViewBag.Title = "Book appointment";
}
<h2>Book appointment</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DoctorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Timeslot)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speciality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>

                @Html.EditorFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DropDownListFor(
    modelItem => item.Timeslot,
    (IEnumerable<SelectListItem>)ViewBag.Timeslot, "Select Time slot"

    )
             
            </td>
            <td>
                <input class="btn btn-primary" name="submitButton" id="btnGet" value="Book Appointmnet" type="button">
               
            </td>
        </tr>

    }
    <tr>
    <input type="hidden" name="Date" value="Date" />
    <input type="hidden" id="DoctorId" value="@ViewBag.DoctorId" />
    <input type="hidden" id="Userid" value="@ViewBag.Userid" />
    </tr>   
</table>


<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">


    $(function () {
     
                debugger;
          $("#item_Timeslot").hide();

                debugger;
        $("#btnGet").click(function () {

            var locid = $('#location option:selected').val();
            var date = $('#item_Date').val();
            var userid = $('#Userid').val();
            var doctorid = $('#DoctorId').val();
            var timeslotid = $("#item_Timeslot option:selected").val()
            debugger;
            if (date == '' || timeslotid == '') {
                alert("Please select date and time slot");

            }
            else {
                window.location.href = '@Url.Action("BookappointmentSucess", "Hospital")?date=' + date + '&userid=' + userid + '&doctorid=' + doctorid + '&timeslotid=' + timeslotid;
            }

        
    });
      });
        $('#item_Date').change(function () {
            var date = $('#item_Date').val();
            var doctorid = $('#DoctorId').val();

            var Timeslot = $('#item_Timeslot');

            var regionsSelect = $('#item_Timeslot');
            regionsSelect.empty();
            if (date != null && date != '') {
                $.getJSON('@Url.Action("Gettimeslotbyavailability")', { doctorid: doctorid, date: date }, function (regions) {
                    if (regions != null && !jQuery.isEmptyObject(regions)) {
                        regionsSelect.append($('<option/>', {
                            value: null,
                            text: "Select Timeslot"
                        }));
                        $.each(regions, function (index, region) {
                            regionsSelect.append($('<option/>', {
                                value: region.Value,
                                text: region.Text
                            }));
                        });

                        $("#item_Timeslot").show();

                    }

                    else {
                        $("#item_Timeslot").hide();
                        alert("No time slot available please select different date")
                    }
                    ;
                   
                });
            }    
        });
</script>

Book_Doctor_appointment/Views/Hospital/Bookappointment_Sucess.cshtml
@{
    ViewBag.Title = "Bookappointment_Sucess";
}

<br />
<span class="alert-success">
    @ViewBag.Message
</span>

   &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
<a href="/Hospital/Myappointments/@ViewBag.Id" class="btn btn-primary btn-lg">My Appointments &raquo;</a>
    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
<a href="/Hospital/Index/@ViewBag.Id" class="btn btn-primary btn-lg">Book Appointment &raquo;</a>
  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
<a href="/Home/Index/" class="btn btn-primary">Logout &raquo;</a>

Book_Doctor_appointment/Views/Hospital/CancelAppointment.cshtml
@{
    ViewBag.Title = "CancelAppointment";
}

<br />
<span class="alert-success">
    @ViewBag.Message
</span>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<a href="/Hospital/Index/@ViewBag.Id" class="btn btn-primary btn-lg">Book Appointment &raquo;</a>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<a href="/Home/Index/" class="btn btn-primary">Logout &raquo;</a>

Book_Doctor_appointment/Views/Hospital/GetListofDoctorforselected.cshtml
@model IEnumerable<Book_Doctor_appointment.Models.Alldoctor>

@{
    ViewBag.Title = "GetListofDoctorforselected";

    var Userid = TempData["Userid"];
}

<h1>Doctors List</h1>
<input type="hidden" id="Userid" value="@ViewBag.Userid" />

@Html.Hidden("Userid", (object)ViewBag.Userid)

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Doctorname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Doctorname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speciality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
              
                @Html.ActionLink("Book Appointment", "Bookappointment", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Book_Doctor_appointment/Views/Hospital/Index.cshtml
@model List<SelectListItem>
@{
    ViewBag.Title = "Index";   
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <br />
    @Html.Hidden("hdnViewBag", (object)ViewBag.Userid)
    <input type="hidden" id="Userid" value="@ViewBag.Userid" />

    @Html.DropDownList("location", Model, new { @id = "location" }) &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
    @Html.DropDownList("Specialty", Model, new { @id = "Specialty" }) &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
    <input class="btn btn-primary" name="submitButton" id="btnGet" value="Search Doctor" type="button">
    <br />
    <br />

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/select2.js"></script>
    <script type="text/javascript">
            $(function () {
              
                $("#btnGet").click(function () {
                    debugger;

                    var locid = $('#location option:selected').val();
                    var Specialty = $('#Specialty option:selected').val();
                    var userid = $('#Userid').val();
                    if (locid == '' || Specialty == '') {
                        alert("Please select Hospital and Speciality to proceed..");
                    }

                    else
 window.location.href = '@Url.Action("GetListofDoctorforselected", "Hospital")?locid='+ locid +'&spid=' + Specialty+'&userid='+userid;
    });
    });
    </script>
</body>
</html>

Book_Doctor_appointment/Views/Hospital/Myappointments.cshtml
@model IEnumerable<Book_Doctor_appointment.Models.Myappointments>

@{
    ViewBag.Title = "Myappointments";
}

<h2>My appointments</h2>

<p>
    <a href="/Hospital/Index/@ViewBag.Userid" class="btn btn-primary btn-default">Book Appointment &raquo;</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DoctorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dateofappointment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Timeslot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Booked_Date)
        </th>
        <th>
             <p>Status</p>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Speciality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateofappointment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timeslot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Booked_Date)
            </td>
            <td>
                @{


                    DateTime today = DateTime.Today;
                }
                @if ((item.Dateofappointment) < today)
                {
                    <p>Done</p> }
                else
                {
                    @Html.ActionLink("Cancel Appointment", "CancelAppointment", new { id = item.Id })
                }

            </td>
        </tr>
    }

</table>

Book_Doctor_appointment/Views/Hospital/Patientappointments.cshtml
@model IEnumerable<Book_Doctor_appointment.Models.Myappointments>

@{
    ViewBag.Title = "Patientappointments";
   
}


<span class="alert-success">
    @ViewBag.name
</span>

<h2>Patient appointments</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emailid)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dateofappointment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timeslot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booked_Date)
            </th>
            <th>
                Status
            </th>
           
        </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Emailid)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dateofappointment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timeslot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Booked_Date)
                </td>

                <td>

                    @{


                        DateTime today = DateTime.Today;
                    }
                    @if ((item.Dateofappointment) < today)
                    {
                        <p style="color:green">Completed</p>
                    }
                    else
                    {
                        <p style="color:red">Pending</p>
                    }
                </td>
            </tr>
                </tbody>
        }

</table>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

@*<script>
    $(function () {
        $(".table").dataTable();
    })
</script>*@